### ISSUE TITLE
The suggestions button appears very tall in mobile

### ISSUE THREAD

**Issue by HightechTR** [IngeniousApplications/IAWEB-Issue#110]
![4E2DB431-CD6A-4649-9A7C-4D20FFE27B02](https://user-images.githubusercontent.com/34486197/83288687-5d81f680-a216-11ea-8dcd-ec22e8093805.png)

**Comment by IngeniousCoder** [comment]
dup #47

**Comment by HightechTR** [comment]
Wat, the issue was about the aesthetics of the button not where it leads to

**Comment by IngeniousCoder** [comment]
yea, it would be reworked either ways because of #47
