### ISSUE TITLE
The website appears to be scrollable horizontally on mobile

### ISSUE THREAD

**Issue by HightechTR** [IngeniousApplications/IAWEB-Issue#114]
![F62A918C-53AA-4426-8857-00F7A95CCAE8](https://user-images.githubusercontent.com/34486197/83318882-884a6a00-a26b-11ea-8373-a98d6e3fb0f1.png)

When scrolled to the right, a white bar appears

**Comment by IngeniousCoder** [comment]
Cannot repro.
