### ISSUE TITLE
This phrase is repeated

### ISSUE THREAD

**Issue by HightechTR** [IngeniousApplications/IAWEB-Issue#115]
![9878695F-E019-41A7-A223-2014E6AF656F](https://user-images.githubusercontent.com/34486197/83318950-54bc0f80-a26c-11ea-8edf-e27a392ab8b1.jpeg)

**Comment by IngeniousCoder** [comment]
suppossed to be deleted with respect to below, but nvm

will remove by 1 mth so will not fix
