### ISSUE TITLE
No logo in top left of Safari Google search

### ISSUE THREAD

**Issue by HightechTR** [IngeniousApplications/IAWEB-Issue#141]
![5B18E543-4C8F-457D-BDB7-1E9C8BDC5C12](https://user-images.githubusercontent.com/34486197/85565704-f7945d80-b661-11ea-89a9-b353e559d811.jpeg)

**Comment by IngeniousCoder** [comment]
@HightechTR seems to be fixed for me.

please confirm if its fixed for you. if it is not, please reopen this issue.
