### ISSUE TITLE
Spell out ETS2, and a few punctuation suggestions

### ISSUE THREAD

**Issue by HightechTR** [IngeniousApplications/IAWEB-Issue#147]
ETS2 should be spelled fully, and there should be spaces in front of the colons

Also, Lego City Undercover has no colon
![546A8618-12DB-442D-86F1-1E331C28B72C](https://user-images.githubusercontent.com/34486197/87227730-8a0d5e80-c3cf-11ea-99b5-45ac5b9bad51.jpeg)

In this one below, use ‘Euro Truck Sim 2 - Around The World’ (with the dash)
![8F32B090-2DCA-4350-9F54-80CCC24F8FA5](https://user-images.githubusercontent.com/34486197/87227745-9e515b80-c3cf-11ea-82ef-69b7871011c0.jpeg)

And uh, there’s no space in front of colons, always...same goes for how Cities: Skylines is stylised
![06EC2A83-AB4E-4CAD-BA4E-0FB2E04A739B](https://user-images.githubusercontent.com/34486197/87227833-f720f400-c3cf-11ea-82a3-8cf3ad2ff546.jpeg)

**Comment by IngeniousCoder** [comment]
fixed remaining issues.

ETS2 will remain short form because the long form causes rendering issues as it is too long.
