### ISSUE TITLE
Incorrect app count as of 2 Dec 2020

### ISSUE THREAD

**Issue by HightechTR** [IngeniousApplications/IAWEB-Issue#150]
Only 1 app as of now

![2CD89456-FDF9-4A0C-AE6D-5618FA1CBF57](https://user-images.githubusercontent.com/34486197/100837782-37caf800-34ac-11eb-8e85-eb34ef09183e.jpeg)

**Comment by IngeniousCoder** [comment]
Staff member count oso wrong

**Comment by IngeniousCoder** [comment]
fixed.
