### ISSUE TITLE
Typewriter text under Latest Update section is not aligned properly (Including how to fix it)

### ISSUE THREAD

**Issue by SNGTech** [IngeniousApplications/IAWEB-Issue#156]
**Bug Description**
Typewriter text is not aligned to the center properly

**URL OF FAULTY SITE**
https://gaming.ingeniousapps.net/

**To Reproduce**
1. Scroll to the Latest Updates section where the typewriter text is.

**Expected behavior**
Typewriter text should be aligned properly

**Fix (SOLUTION)**
_By Editing CSS from Inspection Menu Directly_
1. Open Inspection Menu
2. Inspect the Typewriter text element
3. Go to Styles tab, and add a new a line: `line-height: VALUE` (VALUE can be anything that fits, I found that 1.58 works best at least on my machine)
4. It should auto-update. All edits are client-side so refreshing the page will reset all edits.
Video:
https://user-images.githubusercontent.com/50254849/103119885-50e05680-46b0-11eb-8061-24f56bc6bf09.mp4

_How I Assume You Can Fix It_
1. Go to the website folder location or smth
2. Locate and open the CSS File `custom.css`
3. Add `line-height: VALUE;` after line 454 (VALUE can be anything that fits, I found that 1.58 works best at least on my machine)
4. Save the file and do whatever else to update it on the web

**Comment by IngeniousCoder** [comment]
1.5 is the most accurate value for me. set to 1.5.
