### ISSUE TITLE
IA Gaming footnote not centred

### ISSUE THREAD

**Issue by HightechTR** [IngeniousApplications/IAWEB-Issue#24]
![image](https://user-images.githubusercontent.com/34486197/82749742-eeec0580-9ddd-11ea-8660-2f1441506d38.jpg)

**Comment by IngeniousCoder** [comment]
what footnote?

**Comment by HightechTR** [comment]
![BF8C82C7-67EA-4D8C-BFA5-69498D3CA930](https://user-images.githubusercontent.com/34486197/82750130-b0a41580-9de0-11ea-8d06-9f1cc811f9c8.jpeg)

**Comment by IngeniousCoder** [comment]
intended, not a bug
