### ISSUE TITLE
Streamer graphics can be of same length

### ISSUE THREAD

**Issue by HightechTR** [IngeniousApplications/IAWEB-Issue#25]
![image](https://user-images.githubusercontent.com/34486197/82749787-2a86cf80-9dde-11ea-8af5-d3ece018bd5b.jpg)

**Comment by IngeniousCoder** [comment]
elaborate, i dont understand

**Comment by HightechTR** [comment]
![D61E47EB-C0C9-4B4F-80ED-CE869170EE47](https://user-images.githubusercontent.com/34486197/82750177-e648fe80-9de0-11ea-831a-818e1107cb46.jpeg)

Each box can be made same length if possible

**Comment by IngeniousCoder** [comment]
not possible, it should already be scaled by the CSS
