### ISSUE TITLE
Streamer info not centred

### ISSUE THREAD

**Issue by HightechTR** [IngeniousApplications/IAWEB-Issue#26]
It is actually centred to the footnote which is also not centred (shown in previous issue)

![image](https://user-images.githubusercontent.com/34486197/82749821-6326a900-9dde-11ea-8e44-3b78f932c8a3.jpg)

**Comment by IngeniousCoder** [comment]
dont understand, please elab

**Comment by HightechTR** [comment]
![34D44AC2-0C45-46BB-BBCB-76976C67F9D0](https://user-images.githubusercontent.com/34486197/82750232-36c05c00-9de1-11ea-81aa-dcaea24e8cec.jpeg)

**Comment by IngeniousCoder** [comment]
was made intended this way, there was suppossed to be a sidebar but i removed the sidebar
