### ISSUE TITLE
The elements in Events webpage are not quite centered.

### ISSUE THREAD

**Issue by SNGTech** [IngeniousApplications/IAWEB-Issue#33]
The text "Events Upcoming (And Previous) Events" and the calendar element on the Events webpage is not centered, see the centered rectangle for reference.
![sadda](https://user-images.githubusercontent.com/50254849/82750094-7a669600-9de0-11ea-865e-2953c3dd221b.png)

(Mispelled centered in the img lol)

**Comment by IngeniousCoder** [comment]
<center> Tag was used, i cant do anything else?
