### ISSUE TITLE
Top image in IA Gaming website not mobile-friendly

### ISSUE THREAD

**Issue by HightechTR** [IngeniousApplications/IAWEB-Issue#36]
![958F0A19-4E9C-487F-BD4D-68BE18081AB4](https://user-images.githubusercontent.com/34486197/82760314-4b264800-9e25-11ea-8e21-113061e58252.png)

In mobile, the top image is cropped.
If possible, program the website to simply show a white image on top for the mobile website.

**Comment by IngeniousCoder** [comment]
duplicate #4
