### ISSUE TITLE
Learn More link camouflages with the background

### ISSUE THREAD

**Issue by RichtigSauer** [IngeniousApplications/IAWEB-Issue#48]
![image](https://user-images.githubusercontent.com/53131869/82807213-e79a2a00-9eb9-11ea-932f-d177f3f7fb6c.png)
![image](https://user-images.githubusercontent.com/53131869/82807226-ed900b00-9eb9-11ea-9f28-b5d744ad3061.png)

You cannot see the Learn More text until you hover over it.

**Comment by IngeniousCoder** [comment]
fixed
