### ISSUE TITLE
Improper capitalisation of text under 'The Home of Advanced Applications'

### ISSUE THREAD

**Issue by HightechTR** [IngeniousApplications/IAWEB-Issue#54]
![image](https://user-images.githubusercontent.com/34486197/83227592-203a4c00-a1b7-11ea-856f-b57ad0436087.png)

Should be 'Dedicated to all the internet users...'

**Comment by IngeniousCoder** [comment]
duped case of #? (there are too many cases named 'grammar' i dunno which is the one
