### ISSUE TITLE
Improper punctuation and grammar of 'Awards Winning Developers'

### ISSUE THREAD

**Issue by HightechTR** [IngeniousApplications/IAWEB-Issue#57]
![image](https://user-images.githubusercontent.com/34486197/83227991-fafa0d80-a1b7-11ea-9d2f-d775278b341a.png)

Should be 'Award-winning Developers'

**Comment by HightechTR** [comment]
Issue also present here:
![image](https://user-images.githubusercontent.com/34486197/83230009-99d43900-a1bb-11ea-8cb3-1a4fe8e471e3.png)

**Comment by IngeniousCoder** [comment]
fixed
