### ISSUE TITLE
A lot of unnecessary capitalisation in the 6 features

### ISSUE THREAD

**Issue by HightechTR** [IngeniousApplications/IAWEB-Issue#58]
![image](https://user-images.githubusercontent.com/34486197/83228229-778cec00-a1b8-11ea-8cd7-eca6b99d5397.png)

In order from left to right, top to bottom, should be 'syncing game data', 'name', 'web-based...', 'applications', 'award-winning developers...', 'data', 'security', 'personal data'.

**Comment by IngeniousCoder** [comment]
fixed
