### ISSUE TITLE
Since when did SNGTech play a role in the Minecraft Gameplay Tips

### ISSUE THREAD

**Issue by HightechTR** [IngeniousApplications/IAWEB-Issue#64]
![image](https://user-images.githubusercontent.com/34486197/83229543-bcb21d80-a1ba-11ea-8d77-2e9dde34af08.png)

I recall making the tip video fully by myself without any external help

**Comment by IngeniousCoder** [comment]
i thought the intro video etc from SNGTech?

**Comment by HightechTR** [comment]
Intro animation is to be used in all pre-recorded and edited videos

**Comment by IngeniousCoder** [comment]
ok, i was mistaken, will fix but wont count

**Comment by IngeniousCoder** [comment]
fixed
