### ISSUE TITLE
Prepare for a lot of these English suggestions

### ISSUE THREAD

**Issue by HightechTR** [IngeniousApplications/IAWEB-Issue#74]
![image](https://user-images.githubusercontent.com/34486197/83232475-d30ea800-a1bf-11ea-9c8c-0003b4e72458.png)

Remove the word 'still'

**Comment by IngeniousCoder** [comment]
please dont use grammarly

**Comment by HightechTR** [comment]
The ones highlighted in blue I will ignore from now on, those are the more complex English things

**Comment by IngeniousCoder** [comment]
yes but still i would not want you to use grammarly because it is sort of cheating
