### ISSUE TITLE
Wrong spelling of the word 'Behaviour'

### ISSUE THREAD

**Issue by HightechTR** [IngeniousApplications/IAWEB-Issue#83]
![image](https://user-images.githubusercontent.com/34486197/83233344-2503fd80-a1c1-11ea-8c23-d1ccc2859435.png)

**Comment by HightechTR** [comment]
I officially give up on grammarly and the TNC

**Comment by IngeniousCoder** [comment]
valid, please do not use Grammarly

**Comment by IngeniousCoder** [comment]
fixed
