### ISSUE TITLE
Is this the proper icon for the number of staff members?

### ISSUE THREAD

**Issue by HightechTR** [IngeniousApplications/IAWEB-Issue#91]
![image](https://user-images.githubusercontent.com/34486197/83235215-1c60f680-a1c4-11ea-9db5-ab05c26b1ce2.png)
The icon used is supposed to represent mail.

It should be a person icon or something like:
![image](https://user-images.githubusercontent.com/34486197/83235253-2edb3000-a1c4-11ea-90dc-372e7e52ddbe.png)

**Comment by IngeniousCoder** [comment]
fixed.
