### ISSUE TITLE
Possibly improper icon for number of apps

### ISSUE THREAD

**Issue by HightechTR** [IngeniousApplications/IAWEB-Issue#92]
![image](https://user-images.githubusercontent.com/34486197/83235505-8f6a6d00-a1c4-11ea-9b83-47c7e687ed15.png)
The icon used is supposed to represent cloud storage.

Can be replaced by something like:
![image](https://user-images.githubusercontent.com/34486197/83235468-81b4e780-a1c4-11ea-93ca-767219332a33.png)

**Comment by HightechTR** [comment]
This icon is possible too:
![image](https://user-images.githubusercontent.com/34486197/83235539-a27d3d00-a1c4-11ea-9bca-83acb95be3b9.png)

**Comment by IngeniousCoder** [comment]
chaged to download icon due to flaticon limitations
